### ISSUE TITLE
Blocky

### ISSUE THREAD

**Issue by Leandro-Dalla-Nora** [LongerHV/nixos-configuration#17]
Hi!

You use the blocky, to block ads and telemetry at the file nixos/nasgul/selfhosted/nameserver.nix. I'm using too the blocky, but i can't block the darklist. What's your instalation and configuration tutorial to use this software?

**Comment by LongerHV** [comment]
Hi, there is other part to this configuration [here](https://github.com/LongerHV/nixos-configuration/blob/master/modules/nixos/homelab/blocky.nix) I generally do not follow or make tutorials. Long story short, you need to do couple of things to get blocky to work:
* enable the blocky service
* open UDP port 53 on your firewall
* configure upstream resolver
* configure blacklists
* configure all your devices or DHCP servers to use blocky as the main resolver

Hope this helps
